info:
  project-artifactId: '@project.artifactId@'
  project-author: ${swagger.contact.name}
  project-description: '@project.description@'
  project-finalName: '@project.build.finalName@'
  project-groupId: '@project.groupId@'
  project-name: '@project.name@'
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-spring-boot-version: '@project-parent.version@'
  project-version: '@project.version@'
logging:
  file: /opt/logs/fastspringboot.log
  level:
    io:
      geekidea:
        fastspringboot: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%p]){green} %X{IDENTIFIER}[%t]
            %clr(%logger{36}.%M:%L){cyan} - %m%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%p] %X{IDENTIFIER}[%t] %logger{36}.%M:%L
            - %m%n'
management:
  endpoints:
    web:
      exposure:
        include: '*'
fastspringboot:
  permission:
    interceptor:
      exclude:
        path: /swagger-resources/**,/api-docs/**,/v2/api-docs/**,/adminLogin,/sysLogin,/login.html,/verificationCode,/doc/**,/error/**
      function:
        exclude:
          path: ''
  token:
    timeout:
      interceptor:
        exclude:
          path: /swagger-resources/**,/api-docs/**,/v2/api-docs/**
mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: mysql
      field-strategy: not_empty
      id-type: id_worker
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath*:mapper/**/*Mapper.xml
server:
  servlet:
    context-path: /api
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: UTF-8
spring:
  application:
    name: fast-spring-boot
  banner:
    charset: UTF-8
    image:
      height: 50
      location: logo.png
      margin: 5
      width: 76
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        slf4j:
          enabled: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 3000
        wall:
          config:
            delete-allow: true
            drop-table-allow: false
          enabled: true
      filters: stat,wall,slf4j
      initial-size: 10
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-password: druid123
        login-username: druid
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
  profiles:
    active: '@profileActive@'

  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 100ms

# RabbitMQ 配置
  rabbitmq:
    host: 39.106.37.56
    port: 5672
    username: admin
    password: admin123
    template:
      # 启用重试机制,重试间隔时间为2s,最多重试3次
      retry:
        enabled: true
        initial-interval: 2s
        max-attempts: 3
      queue: fast-spring-boot-queue
      # 定义默认的交换机名称
      exchange: fast-spring-boot-exchange
      # 定义默认的路由key
      routing-key: fast-spring-boot-key

  kafka:
    bootstrap-servers: 203.104.37.38:9092
    producer:
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
    consumer:
      group-id: fast-spring-boot-group
    template:
      default-topic: fast-spring-boot-topic



swagger:
  base:
    package: io.geekidea.fastspringboot
  contact:
    email: geekidea@qq.com
    name: liujixiang
    url: ''
  description: ''
  title: fast-spring-boot
  url: ''
  version: 1.0

hello: hello....