fastspringboot:
  isEnableAnsi: false
  login:
    token:
      valid:
        time:
          minute: 3600
logging:
  level:
    io:
      geekidea:
        fastspringboot: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO
server:
  port: 8888
  servlet:
    context-path: /api
spring:
  datasource:
    password: ''
    url: ''
    username: ''
  redis:
    database: 0
    host: ''
    password: ''
    port: 6379
