fastspringboot:
  isEnableAnsi: true
  login:
    token:
      valid:
        time:
          minute: 3600
logging:
  level:
    io:
      geekidea:
        fastspringboot: DEBUG
    org:
      springframework:
        web: INFO
    root: INFO
server:
  port:
  servlet:
    context-path: /
spring:
  datasource:
    # MySQL 配置
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net:3306/ad_e0bb86345fd1aed?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: b7ebc6f5161e8e
    password: 2a3b1127

  # Redis 配置
  redis:
    database: 0
    host: redis-16667.c15.us-east-1-4.ec2.cloud.redislabs.com
    password: M0VICgMfPK1j3HmjRKf1srtDupCmusuQ
    port: 16667

  # RabbitMQ 配置
  rabbitmq:
    host: barnacle.rmq.cloudamqp.com
    port: 1883
    username: zhjajlkp
    password: g0Krc3Nu-BnI8wVipmcR8sIQrBZzjlWg
    template:
      # 启用重试机制,重试间隔时间为2s,最多重试3次
      retry:
        enabled: true
        initial-interval: 2s
        max-attempts: 3
      queue: fast-spring-boot-queue
      # 定义默认的交换机名称
      exchange: fast-spring-boot-exchange
      # 定义默认的路由key
      routing-key: fast-spring-boot-key

